spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:foo;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties.javax.persistence.validation.mode: auto