version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: gradle dependencies

  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: gradle test
      - run: gradle jacocoTestReport
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test