version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: gradle dependencies

  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: gradle test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



#version: 2
#jobs:
#
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk
#
#
#    working_directory: ~/circle
#
#    environment:
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#
#    steps:
#      - checkout
#
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "build.gradle" }}
#          - v1-dependencies-
#
#      - run: gradle dependencies
#
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
#
#      - run: gradle test